name: ft-embedding-blog
channels:
  - defaults
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - cudatoolkit=11.8.0
  - faiss=1.7.4
  - faiss-gpu=1.7.4
  - intel-openmp=2021.4.0
  - ld_impl_linux-64=2.40
  - libblas=3.9.0
  - libcblas=3.9.0
  - libfaiss=1.7.4
  - libfaiss-avx2=1.7.4
  - libffi=3.4.4
  - libgcc-ng=13.2.0
  - libgomp=13.2.0
  - liblapack=3.9.0
  - libstdcxx-ng=13.2.0
  - libuuid=1.41.5
  - mkl=2021.4.0
  - ncurses=6.5
  - numpy=1.26.4
  - openssl=3.3.0
  - pip=24.0
  - python=3.11.9
  - python_abi=3.11
  - readline=8.2
  - setuptools=69.5.1
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - accelerate==0.30.1
      - aenum==3.1.15
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - annotated-types==0.6.0
      - anthropic==0.23.1
      - anyio==4.3.0
      - asttokens==2.4.1
      - attrs==23.2.0
      - beautifulsoup4==4.12.3
      - blis==0.7.11
      - boto3==1.34.131
      - botocore==1.34.131
      - catalogue==2.0.10
      - certifi==2024.2.2
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpathlib==0.16.0
      - cloudpickle==2.2.1
      - cohere==5.5.0
      - comm==0.2.2
      - confection==0.1.4
      - cryptography==42.0.7
      - cymem==2.0.8
      - dataclasses-json==0.6.6
      - datasets==2.19.1
      - debugpy==1.8.1
      - decorator==5.1.1
      - deprecated==1.2.14
      - dill==0.3.8
      - dirtyjson==1.0.8
      - distro==1.9.0
      - docker==7.0.0
      - executing==2.0.1
      - fastavro==1.9.4
      - filelock==3.14.0
      - flagembedding==1.2.9
      - frozenlist==1.4.1
      - fsspec==2024.3.1
      - google-pasta==0.2.0
      - gradientai==1.12.1
      - greenlet==3.0.3
      - h11==0.14.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - httpx-sse==0.4.0
      - huggingface-hub==0.23.0
      - idna==3.7
      - importlib-metadata==6.11.0
      - ipykernel==6.29.4
      - ipython==8.24.0
      - ipywidgets==8.1.2
      - jedi==0.19.1
      - jinja2==3.1.4
      - jmespath==1.0.1
      - joblib==1.4.2
      - jsonpatch==1.33
      - jsonpath-ng==1.6.1
      - jsonpointer==2.4
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.1
      - jupyter-core==5.7.2
      - jupyterlab-widgets==3.0.10
      - langchain==0.1.20
      - langchain-aws==0.1.4
      - langchain-community==0.0.38
      - langchain-core==0.1.52
      - langchain-text-splitters==0.0.1
      - langcodes==3.4.0
      - langsmith==0.1.58
      - language-data==1.2.0
      - llama-index==0.10.37
      - llama-index-agent-openai==0.2.5
      - llama-index-cli==0.1.12
      - llama-index-core==0.10.37
      - llama-index-embeddings-adapter==0.1.3
      - llama-index-embeddings-bedrock==0.1.5
      - llama-index-embeddings-huggingface==0.2.0
      - llama-index-embeddings-openai==0.1.9
      - llama-index-finetuning==0.1.5
      - llama-index-indices-managed-llama-cloud==0.1.6
      - llama-index-legacy==0.9.48
      - llama-index-llms-anthropic==0.1.11
      - llama-index-llms-anyscale==0.1.4
      - llama-index-llms-bedrock==0.1.8
      - llama-index-llms-gradient==0.1.2
      - llama-index-llms-langchain==0.1.3
      - llama-index-llms-openai==0.1.19
      - llama-index-multi-modal-llms-openai==0.1.6
      - llama-index-postprocessor-cohere-rerank==0.1.6
      - llama-index-program-openai==0.1.6
      - llama-index-question-gen-openai==0.1.3
      - llama-index-readers-file==0.1.22
      - llama-index-readers-llama-parse==0.1.4
      - llama-parse==0.4.3
      - llamaindex-py-client==0.1.19
      - lm-cocktail==0.0.4
      - marisa-trie==1.1.1
      - markupsafe==2.1.5
      - marshmallow==3.21.2
      - matplotlib-inline==0.1.7
      - minijinja==2.0.1
      - mpmath==1.3.0
      - multidict==6.0.5
      - multiprocess==0.70.16
      - murmurhash==1.0.10
      - mypy-extensions==1.0.0
      - nest-asyncio==1.6.0
      - networkx==3.3
      - nltk==3.8.1
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.1.105
      - openai==1.30.1
      - orjson==3.10.3
      - packaging==23.2
      - pandas==2.2.2
      - parso==0.8.4
      - pathos==0.3.2
      - pexpect==4.9.0
      - pillow==10.3.0
      - platformdirs==4.2.2
      - ply==3.11
      - pox==0.3.4
      - ppft==1.7.6.8
      - preshed==3.0.9
      - prompt-toolkit==3.0.43
      - protobuf==4.25.3
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyarrow==16.1.0
      - pyarrow-hotfix==0.6
      - pycparser==2.22
      - pydantic==1.10.15
      - pydantic-core==2.18.2
      - pygments==2.18.0
      - pypdf==4.2.0
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyyaml==6.0.1
      - pyzmq==26.0.3
      - referencing==0.35.1
      - regex==2024.5.10
      - requests==2.31.0
      - rpds-py==0.18.1
      - s3transfer==0.10.1
      - safetensors==0.4.3
      - sagemaker==2.224.0
      - schema==0.7.7
      - scikit-learn==1.4.2
      - scipy==1.13.0
      - sentence-transformers==2.7.0
      - six==1.16.0
      - smart-open==6.4.0
      - smdebug-rulesconfig==1.0.1
      - sniffio==1.3.1
      - soupsieve==2.5
      - spacy==3.7.4
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - sqlalchemy==2.0.30
      - srsly==2.4.8
      - stack-data==0.6.3
      - striprtf==0.0.26
      - sympy==1.12
      - tblib==3.0.0
      - tenacity==8.3.0
      - thinc==8.2.3
      - threadpoolctl==3.5.0
      - tiktoken==0.7.0
      - tokenizers==0.19.1
      - torch==2.3.0
      - tornado==6.4
      - tqdm==4.66.4
      - traitlets==5.14.3
      - transformers==4.40.2
      - triton==2.3.0
      - typer==0.9.4
      - types-requests==2.31.0.20240406
      - typing-extensions==4.11.0
      - typing-inspect==0.9.0
      - tzdata==2024.1
      - urllib3==2.2.1
      - wasabi==1.1.2
      - wcwidth==0.2.13
      - weasel==0.3.4
      - widgetsnbextension==4.0.10
      - wrapt==1.16.0
      - xxhash==3.4.1
      - yarl==1.9.4
      - zipp==3.18.1
